import express from "express";
import cors from "cors";
import cryptoRouter from "./controller/cryptoController.js";
const app = express();
app.use(cors());
app.use(express.json({ limit: "1mb" }));
app.get("/", (req, res) => res.json({ message: "CipherWeb API is running" }));
app.use("/api/crypto", cryptoRouter);
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
